apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent
  namespace: default
data:
  fluent_conf: |
    @include kubernetes.conf

    <match **flink**>
      @type kafka_buffered

      brokers             {{ include "kafka.fullname" . }}:9092

      topic_key             log-analysis
      default_topic         log-analysis
      output_data_type      json
      output_include_tag    true
      output_include_time   true
      get_kafka_client_log  false
      flush_interval        1s

      required_acks         1
      compression_codec     gzip
    </match>
