apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluent.fullname" . }}
  namespace: default
data:
  fluent_conf: |
    <source>
      @type syslog
      @log_level trace
      port 5140
      bind 0.0.0.0
      protocol_type tcp
      tag cf.app

      frame_type octet_count

      <parse>
        message_format rfc5424
      </parse>
    </source>

    <match **>
      @type kafka_buffered
      @log_level debug
      brokers               {{ include "kafka.fullname" . }}:9092
      topic_key             log-analysis
      default_topic         log-analysis
      output_include_tag    true
      output_include_time   true
      get_kafka_client_log  false
      flush_interval        5s
      disable_retry_limit   true
      required_acks         1
      compression_codec     gzip
    </match>