apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fluent.fullname" . }}
  namespace: default
  labels:
    k8s-app: {{ template "fluent.fullname" . }}
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: {{ template "fluent.fullname" . }}
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      replicas: 1
      hostNetwork: true
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.1.3-debian-elasticsearch
          command: ["/bin/sh"]
          args: ["-c", "gem install fluent-plugin-kafka && cp /fluent-config/fluent.conf /fluentd/etc/ && /fluentd/entrypoint.sh"]
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            exec:
              command:
                - '/bin/sh'
                - '-c'
                - >
                  exit 0
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            exec:
              command:
                - '/bin/sh'
                - '-c'
                - >
                  exit 0
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-config
              mountPath: /fluent-config
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-config
          configMap:
            name: {{ template "fluent.fullname" . }}
            items:
              - key: fluent_conf
                path: fluent.conf
