apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fluent.fullname" . }}
  labels:
    app: {{ template "fluent.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  template:
    metadata:
      labels:
        app: {{ template "fluent.fullname" . }}
        k8s-app: {{ template "fluent.fullname" . }}
    spec:
      containers:
        - name: {{ template "turbo-logz-user-api.fullname" . }}-test
          image: fluent/fluentd-kubernetes-daemonset:v1.1.3-debian-elasticsearch
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          command: ["/bin/sh"]
          args: ["-c", "gem install fluent-plugin-kafka && cp /fluent-config/fluent.conf /fluentd/etc/ && /fluentd/entrypoint.sh"]
          ports:
            - name: syslog
              containerPort: 5140
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-config
              mountPath: /fluent-config
          resources:
            requests:
              memory: 120Mi
              cpu: 10m
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-config
          configMap:
            name: {{ template "fluent.fullname" . }}
            items:
              - key: fluent_conf
                path: fluent.conf
