kind: Service
apiVersion: v1
metadata:
  name: {{ template "fluent.fullname" . }}
  labels:
    app: {{ template "fluent.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: LoadBalancer
  selector:
    app: {{ template "fluent.fullname" . }}
  ports:
    - name: syslog
      protocol: TCP
      port: 5140
      targetPort: syslog