apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations: {}
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 2181
    targetPort: client
    protocol: TCP
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
