apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: server
spec:
  serviceName: {{ template "zookeeper.fullname" . }}-headless
  replicas: 3
  selector:
    matchLabels:
      app: {{ template "zookeeper.name" . }}
      release: {{ .Release.Name }}
      component: server
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: {{ template "zookeeper.name" . }}
        release: {{ .Release.Name }}
        component: server
      annotations: {}
    spec:
      terminationGracePeriodSeconds: 1800
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      priorityClassName: ""
      containers:
      - name: zookeeper
        image: "gcr.io/google_samples/k8szk:v3"
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -xec
          - zkGenConfig.sh && exec zkServer.sh start-foreground
        ports:
          - name: client
            containerPort: 2181
            protocol: TCP
          - name: election
            containerPort: 3888
            protocol: TCP
          - name: server
            containerPort: 2888
            protocol: TCP
        livenessProbe:
          exec:
            command:
              - zkOk.sh
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command:
              - zkOk.sh
          initialDelaySeconds: 20
        env:
        - name: ZK_REPLICAS
          value: "3"
        - name: JMXAUTH
          value: "false"
        - name: JMXDISABLE
          value: "false"
        - name: JMXPORT
          value: "1099"
        - name: JMXSSL
          value: "false"
        - name: ZK_CLIENT_PORT
          value: "2181"
        - name: ZK_ELECTION_PORT
          value: "3888"
        - name: ZK_HEAP_SIZE
          value: "2G"
        - name: ZK_INIT_LIMIT
          value: "5"
        - name: ZK_LOG_LEVEL
          value: "INFO"
        - name: ZK_MAX_CLIENT_CNXNS
          value: "60"
        - name: ZK_MAX_SESSION_TIMEOUT
          value: "40000"
        - name: ZK_MIN_SESSION_TIMEOUT
          value: "4000"
        - name: ZK_PURGE_INTERVAL
          value: "0"
        - name: ZK_SERVER_PORT
          value: "2888"
        - name: ZK_SNAP_RETAIN_COUNT
          value: "3"
        - name: ZK_SYNC_LIMIT
          value: "10"
        - name: ZK_TICK_TIME
          value: "2000"
        resources: {}
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper
      nodeSelector: {}
      affinity: {}
      tolerations: []
      volumes:
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: "standard"
