apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "turbo-logz-gateway.fullname" . }}
  labels:
    app: {{ template "turbo-logz-gateway.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "turbo-logz-gateway.fullname" . }}
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
        - name: {{ template "turbo-logz-gateway.fullname" . }}
          image: "{{ .Values.turboLogzGateway }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          ports:
            - containerPort: 80
          env:
            - name: LOG_LEVEL
              value: debug
            - name: GRAPHQL_URL
              value: http://{{ template "turbo-logz-graphql.fullname" . }}
            - name: WS_URL
              value: http://{{ template "turbo-logz-graphql.fullname" . }}:3000/
            - name: UI_URL
              value: http://{{ template "turbo-logz-ui.fullname" . }}
            - name: FLINK_URL
              value: http://{{ template "flink.fullname" . }}-jobmanager:8081/
          resources:
            requests:
              memory: 80Mi
              cpu: 10m
