apiVersion: v1
kind: Service
metadata:
  name: {{ template "turbo-logz-graphql.fullname" . }}
  labels:
    app: {{ template "turbo-logz-graphql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  sessionAffinity: ClientIP
  ports:
    - name: {{ template "turbo-logz-graphql.fullname" . }}
      port: 80
      targetPort: 80
    - name: {{ template "turbo-logz-graphql.fullname" . }}-ws
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ template "turbo-logz-graphql.fullname" . }}
