apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kafka-manager.fullname" . }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "kafka-manager.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "kafka-manager.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kafka-manager.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: zenko/kafka-manager:1.3.3.18
          imagePullPolicy: IfNotPresent
          ports:
            - name: kafka-manager
              containerPort: 9000
              protocol: TCP
          env:
            - name: ZK_HOSTS
              value: {{ template "zookeeper.fullname" . }}
            - name: JAVA_OPTS
              value: ""
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "kafka-manager.fullname" . }}
                  key: applicationSecret
            - name: KAFKA_MANAGER_AUTH_ENABLED
              value: "false"
            - name: KAFKA_MANAGER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "kafka-manager.fullname" . }}
                  key: basicAuthUsername
            - name: KAFKA_MANAGER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "kafka-manager.fullname" . }}
                  key: basicAuthPassword
          livenessProbe:
            httpGet:
              path: /api/health
              port: kafka-manager
          readinessProbe:
            httpGet:
              path: /api/health
              port: kafka-manager
          resources:
