apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka-manager.fullname" . }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" | trunc 63 }}
spec:
  type: ClusterIP
  ports:
    - name: kafka-manager
      port: 9000
      targetPort: kafka-manager
      protocol: TCP
  selector:
    app: {{ template "kafka-manager.fullname" . }}
    release: {{ .Release.Name }}
