apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "flink.fullname" . }}-hadoop-config
  labels:
    app: {{ template "flink.fullname" . }}
data:
  core-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration/>
