apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "flink.fullname" . }}-flink-config
  labels:
    app: {{ template "flink.fullname" . }}
data:
  flink-conf.yaml: |
    blob.server.port: 6124
    jobmanager.rpc.address: {{ template "flink.fullname" . }}-jobmanager
    jobmanager.rpc.port: 6123
    jobmanager.heap.mb: 1024
    taskmanager.heap.mb: 1024
    taskmanager.numberOfTaskSlots: 1
    jobmanager.web.log.path: /opt/flink/log/output.log
    taskmanager.log.path: /opt/flink/log/output.out
  log4j-console.properties: |
    log4j.rootLogger=INFO, console, file, stdout
    # Uncomment this if you want to _only_ change Flink's logging
    #log4j.logger.org.apache.flink=INFO
    # The following lines keep the log level of common libraries/connectors on
    # log level INFO. The root logger does not override this. You have to manually
    # change the log levels here.
    log4j.logger.akka=INFO
    log4j.logger.org.apache.kafka=INFO
    log4j.logger.org.apache.hadoop=INFO
    log4j.logger.org.apache.zookeeper=INFO
    # Suppress the irrelevant (wrong) warnings from the Netty channel handler
    log4j.logger.org.jboss.netty.channel.DefaultChannelPipeline=ERROR, console
    # Log all infos to the console
    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.layout=org.apache.log4j.PatternLayout
    log4j.appender.console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
    #define stdout file
    log4j.appender.stdout=org.apache.log4j.FileAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.file=/opt/flink/log/output.out