apiVersion: v1
kind: Service
metadata:
  name: {{ template "cassandra.fullname" . }}
  labels:
    app: {{ template "cassandra.fullname" . }}
spec:
  ports:
    - port: 9042
  selector:
    app: {{ template "cassandra.fullname" . }}