apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "kafka.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Name }}
    release: {{ .Release.Service }}
  name: {{ template "kafka.fullname" . }}-config
data:
  runtimeConfig.sh: |
    #!/bin/bash
    set -e
    cd /usr/bin
    until kafka-configs --zookeeper {{ template "zookeeper.fullname" . }} --entity-type topics --describe || (( count++ >= 6 ))
    do
      echo "Waiting for Zookeeper..."
      sleep 20
    done
    until nc -z {{ template "kafka.fullname" . }} 9092 || (( retries++ >= 6 ))
    do
      echo "Waiting for Kafka..."
      sleep 20
    done

    kafka-topics --zookeeper {{ template "zookeeper.fullname" . }} --create --if-not-exists --force --topic unicron-tasks-log --partitions 1 --replication-factor 1
