apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    app: {{ include "kafka.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ include "kafka.fullname" . }}-headless
  selector:
    matchLabels:
      app: {{ template "kafka.fullname" . }}
      release: {{ .Release.Name }}
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: "OnDelete"
  {{ if eq .Values.environment "dev" }}
  replicas: 2
  {{ else }}
  replicas: 4
  {{ end }}
  template:
    metadata:
      annotations: {}
      labels:
        app: {{ include "kafka.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      tolerations: []
      affinity: {}
      nodeSelector: {}
      containers:
      - name: {{ include "kafka.fullname" . }}-broker
        image: confluentinc/cp-kafka:5.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
              - sh
              - -ec
              - /usr/bin/jps | /bin/grep -q SupportedKafka
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: kafka
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        ports:
          - containerPort: 9092
            name: kafka
        resources:
          limits:
            cpu: 200m
            memory: 1536Mi
          requests:
            cpu: 100m
            memory: 1024Mi
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx1G -Xms1G"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: {{ template "zookeeper.fullname" . }}
    # This is required because the Downward API does not yet support identification of
    # pod numbering in statefulsets. Thus, we are required to specify a command which
    # allows us to extract the pod ID for usage as the Kafka Broker ID.
    # See: https://github.com/kubernetes/kubernetes/issues/31218
        command:
        - sh
        - -exc
        - |
          unset KAFKA_PORT && \
          export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
          export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092 && \
          exec /etc/confluent/docker/run
        volumeMounts:
        - name: datadir
          mountPath: "/opt/kafka/data"
      volumes:
      terminationGracePeriodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "1Gi"
      storageClassName: "standard"

